### PR TITLE
Modify the Dockerfile to avoid rebuild after changing config & minor fixes

### PR DESCRIPTION
**Pull request by ButterCatz**
Modify the Dockerfile so the builder no longer needs to `COPY` the config files. This prevents the rebuild after changing configs.

### CODE REVIEW

**Comment by ButterCatz** [comment]
Add a new command `clear` for clearing the whole playlist.
Improve the readability

**Comment by phoxwupsh** [comment]
Thanks a lot for help🙏

**Comment by ButterCatz** [comment]
@phoxwupsh, do you plan on supporting prefix calls for all the commands? I forgot to remove the `prefix_command` in `clear.rs` I wrote for testing.

**Comment by phoxwupsh** [comment]
I've noticed that, it will be removed before next version update.

**Pull request merged**
